# Generated by Django 5.1.6 on 2025-02-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muallim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=200)),
                ('familiyasi', models.CharField(max_length=200)),
                ('yoshi', models.IntegerField(default=1)),
                ('ilmiy_salohiyati', models.CharField(max_length=200)),
                ('mutaxassisligi', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Muallim',
                'verbose_name_plural': 'Muallimlar',
                'db_table': 'Muallim',
            },
        ),
    ]
