# Generated by Django 5.1.6 on 2025-02-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='yangliklar')),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('izoh', models.TextField(max_length=2000, verbose_name='izoh')),
            ],
            options={
                'verbose_name': 'News',
                'db_table': 'News',
            },
        ),
        migrations.AlterModelOptions(
            name='muallim',
            options={'verbose_name': 'Muallim'},
        ),
    ]
